/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoieRouteImport } from './routes/apoie'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as PadariaRouteImport } from './routes/padaria'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoieRoute = ApoieRouteImport.update({
  id: '/apoie',
  path: '/apoie',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const PadariaRoute = PadariaRouteImport.update({
  id: '/padaria',
  path: '/padaria',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoie': typeof ApoieRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/padaria': typeof PadariaRoute
  '/painel': typeof PainelRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoie': typeof ApoieRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/padaria': typeof PadariaRoute
  '/painel': typeof PainelRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoie': typeof ApoieRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/inscricao': typeof InscricaoRoute
  '/padaria': typeof PadariaRoute
  '/painel': typeof PainelRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sobre': typeof SobreRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apoie'
    | '/cadastro'
    | '/contato'
    | '/entrar'
    | '/inscricao'
    | '/padaria'
    | '/painel'
    | '/recuperar-senha'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apoie'
    | '/cadastro'
    | '/contato'
    | '/entrar'
    | '/inscricao'
    | '/padaria'
    | '/painel'
    | '/recuperar-senha'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos'
  id:
    | '__root__'
    | '/'
    | '/apoie'
    | '/cadastro'
    | '/contato'
    | '/entrar'
    | '/inscricao'
    | '/padaria'
    | '/painel'
    | '/recuperar-senha'
    | '/sobre'
    | '/cursos/$slug'
    | '/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoieRoute: typeof ApoieRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  InscricaoRoute: typeof InscricaoRoute
  PadariaRoute: typeof PadariaRoute
  PainelRoute: typeof PainelRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SobreRoute: typeof SobreRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoie': {
      id: '/apoie'
      path: '/apoie'
      fullPath: '/apoie'
      preLoaderRoute: typeof ApoieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padaria': {
      id: '/padaria'
      path: '/padaria'
      fullPath: '/padaria'
      preLoaderRoute: typeof PadariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoieRoute: ApoieRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  InscricaoRoute: InscricaoRoute,
  PadariaRoute: PadariaRoute,
  PainelRoute: PainelRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SobreRoute: SobreRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
